interface GameDetailed extends Object {
    away_team_code: string,
    away_team_result: number,
    game_center_active: boolean,
    game_id: number,
    game_type: string,
    game_uuid: string,
    highlights_coverage_enabled: boolean,
    home_team_code: string,
    home_team_result: number,
    live: any,
    live_coverage_enabled: boolean,
    overtime: boolean,
    penalty_shots: boolean,
    played: boolean,
    round_number: number,
    season: string,
    series: string,
    start_date_time: string
}